Enabled golden image validation on GitHub CI (#50)

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -2,6 +2,12 @@ name: Win32/UWP build
 
 on: [push, pull_request]
 
+env:
+  # 'capture'        - generate golden images
+  # 'compare'        - render and compare with the references
+  # 'compare_update' - first compare with the references and then update them
+  test_mode: compare_update
+
 jobs:
   precheks:
     name:    Win10 -> Pre-checks
@@ -23,13 +29,14 @@ jobs:
       shell: cmd
       working-directory: ${{github.workspace}}/DiligentSamples/BuildTools/FormatValidation
       run: validate_format_win.bat
-    
+
 
   build:
     needs:   precheks
     runs-on: windows-2022
 
     strategy:
+      fail-fast: false
       matrix:
         name:            ["Win10"]
         toolset:         ["Win32", "x64"]
@@ -85,8 +92,14 @@ jobs:
     name: Win10 -> ${{ matrix.name }}-${{ matrix.toolset }}, ${{ matrix.build_type }}
 
     steps:
-    - name: Checkout
+    - name: Checkout Code Base
       uses: DiligentGraphics/github-action/checkout@v1
+
+    - name: Checkout Test Data
+      uses: actions/checkout@v2
+      with:
+        repository: DiligentGraphics/DiligentTestData
+        path:       DiligentTestData
 
     - name: Set up build environment
       if:   success()
@@ -106,5 +119,37 @@ jobs:
         cmake-args: ${{ matrix.cmake_args }}
 
     - name: Build
+      id:   build
       if:   success()
       uses: DiligentGraphics/github-action/build@v1
+
+    - name: Run Sample Tests D3D11
+      working-directory: ${{github.workspace}}/DiligentSamples/Tests
+      if:   ${{ matrix.name == 'Win10' || matrix.name == 'Win8.1' }}
+      shell: cmd
+      run: |
+        :: Run Sample Tests D3D11
+        set golden_images_root_dir=${{github.workspace}}/DiligentTestData/GoldenImages
+        ProcessGoldenImages.bat ${{env.DILIGENT_BUILD_DIR}} ${{matrix.build_type}} ${{env.test_mode}} "--mode d3d11 --adapter sw"
+
+    - name: Run Sample Tests D3D12
+      working-directory: ${{github.workspace}}/DiligentSamples/Tests
+      # NB: it is essential to include failure() to override the default status check of success()
+      #     that is automatically applied to if conditions that don't contain a status check function.
+      if:   ${{ (success() || failure() && steps.build.outcome == 'success') && matrix.name == 'Win10' }}
+      shell: cmd
+      run: |
+        :: Run Sample Tests D3D12
+        set golden_images_root_dir=${{github.workspace}}/DiligentTestData/GoldenImages
+        ProcessGoldenImages.bat ${{env.DILIGENT_BUILD_DIR}} ${{matrix.build_type}} ${{env.test_mode}} "--mode d3d12 --adapter sw"
+
+    - name: Upload Golden Images
+      uses: actions/upload-artifact@v2
+      # NB: it is essential to include failure() to override the default status check of success()
+      #     that is automatically applied to if conditions that don't contain a status check function.
+      if: ${{ (success() || failure() && steps.build.outcome == 'success') && (matrix.name == 'Win10' || matrix.name == 'Win8.1') }}
+      with:
+        name: GoldenImages-${{ matrix.name }}-${{ matrix.toolset }}-${{ matrix.build_type }}
+        path: |
+          ${{github.workspace}}/DiligentTestData/GoldenImages
+        retention-days: 90
